### ISSUE TITLE
Special characters in text modifiers

### ISSUE THREAD

**Issue by canadajebus** [spatialillusions/milsymbol#111]
I have encountered an error when using special characters in text modifiers. Eg: é (alt+0233).

The problem arises only when using symbol.toDataURL()   This creates "data:image/svg+xml;base64...." which doesn't seem to allow those special characters. In IE it actually outputs "XML5617: Illegal XML character" to the console.

I was able to get it working by using  symbol.asCanvas(window.devicePixelRatio).toDataURL() instead.  Doing this creates "data:image/png;base64...." 

Not sure if this is a bug with your code really, but maybe a check is necessary to handle these characters.

**Comment by spatialillusions** [comment]
This is because of what characters that are allowed when you base64 encode a string. It should be quite straight forward to make some changes to the toDataURL method to solve this problem if one of the solutions here was used:
https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding
It would be much appriciated if you tested this with your data and made a pull request, otherwise I will look into it when I find some time.

**Comment by spatialillusions** [comment]
Another way that could be faster is to simply replace the special characters with the unicode representation. So replacing é with &#223; would make it work. You can loop your string and use charCodeAt(i) for each character to get the char code and then your strings should work. I have done this in the sample situation.js where the swedish character ä is encoded with &#228;

**Comment by spatialillusions** [comment]
I have tried to figure out another way to solve this, but it is kind of tricky. Since if I modify the text fields the DOM output will stop working, so I would have to modify them temorary in the toDataURL method, and this would slow things down, so the best thing is that the developer modifies the input based on what method that will be used.
Could you close this issue if this solves your problem, or suggest another way this could be solved?

**Comment by canadajebus** [comment]
I'll close the issue, just using symbol.asCanvas(window.devicePixelRatio).toDataURL() seems to work fine for my app.
