### ISSUE TITLE
Monocolor status symbols being used even though this option is not specified (MIL-STD-2525D)

### ISSUE THREAD

**Issue by jamjar919** [spatialillusions/milsymbol#118]
From a new repo, with only milsymbol installed (From NPM), rendering the SIDC `10000030000000000000` for an unknown damaged unit. 

Goal (From [the unit generator](https://spatialillusions.com/unitgenerator.html#10000030000000000000)): 
![Goal](http://i.imgur.com/vAu7DvV.png)

Result (From a fresh milsymbol install):
![Result](http://i.imgur.com/k77wcIg.png)

The code I have used to generate the image is shown below.
```
const ms = require('milsymbol');
var fs = require('fs');

const symbol = new ms.Symbol("10000030000000000000", {
	size: 50,
});
fs.writeFile("output.svg", symbol.asSVG(), function(){});
```

It seems to be using the status indicators usually reserved for the icons drawn in one color. Is this desired behaviour? If so is there an option I can use that will switch to the version shown in the unit generator? I'm on node `v6.11.0` and npm `5.0.4` on Windows if that is useful.

**Comment by jamjar919** [comment]
Oh, and `milsymbol.js 1.2.1`

**Comment by spatialillusions** [comment]
You are correct, this is (was) a bug that was caused by that monoColor was initialized as `false` instead of an empty string. I have now patched the master branch with a fix for this. 

I will within a week release a new version of milsymbol that includes this and some other minor fixes, but the simplest workaround right now is to simply set monoColor to an empty string when you initiate your symbol:

```js
const ms = require("milsymbol");
var fs = require("fs");

const symbol = new ms.Symbol("10000030000000000000", {
  size: 50, 
  monoColor: ""
});
fs.writeFile("output.svg", symbol.asSVG(), function() {});
```

**Comment by jamjar919** [comment]
Great, thanks for all your work!
