### ISSUE TITLE
AIR amplifier wrong position?

### ISSUE THREAD

**Issue by Codingboy** [spatialillusions/milsymbol#119]
As like in http://explorer.milsymb.net/#/explore/ an helo should look like this:
https://gyazo.com/36d75ef86506e1c37df4c0b8952995a8
yours look like this:
https://gyazo.com/7fe77da3332ecfbce6e079878fa2606f
I am not sure what the specification says,
if yours is correct, just forward the issue to the other project :P

I use version ## 1.2.1 12 JUN 2017

**Comment by spatialillusions** [comment]
This is a bit tricky, if we look in MIL-STD-2525D, the unit size modifiers are not specified for air symbols. Compare figure C-3 and figure D-3 here http://www.dtic.mil/doctrine/doctrine/other/ms_2525d.pdf

What happens in the milsymb explorer is that the unit size modifiers are drawn in the position that they would be for land unit frames, and they are not move based on the size of the frame. So if you change the symbol to neutral instead of friend it will suddenly be outside of the frame.
![neutral](https://user-images.githubusercontent.com/8155542/27945726-9731f7e6-62ee-11e7-8fd1-4f86a0687b8a.PNG)

Since I know that users want to set the unit size modifier on all types of symbols the approach in milsymbol is a bit more complex, where I take the intent of land units (that the modifier should be on top of the frame) and apply it to all type of frames, so that the modifier is not defined in a fixed place and instead as a small offset from the frame. 

So to answer your question:
I think that the way that milsymbol draws the symbol is correct. And I also think that it is handled correct in milsymb since you shouldn't use the unit size modifier on air symbols.
Does this explanation make sense for you?

**Comment by Codingboy** [comment]
It is all fine! I just noticed the difference and thought might be good to tell.
For my application it is good, to also be able to set the amplifier no matter what the spec says :D
