### ISSUE TITLE
Turn off attribution in the console log

### ISSUE THREAD

**Issue by jziggas** [spatialillusions/milsymbol#128]
It would be nice to be able to turn off the attribution information that is logged out to the browser console, e.g.
> milsymbol.js 1.2.1 - Copyright (c) 2017 Måns Beckman  http://www.spatialillusions.com

**Comment by spatialillusions** [comment]
I can understand your point, at the same time I have a reason for printing the attribution information to the console. 
The MIT license requires attribution, and I know that there is a lot of developers who "forget" to give attribution to the libraries that they use. And since most users of milsymbol can't even tell me that they are using milsymbol, since defense systems and big corporations, it is nice to know that at least I get my name on the console in some systems and if I should stumble upon a system I can simply view the console and see if they are using my code. (I have spent more time than I want to think about developing milsymbol, and all is done during evenings and weekends without any funding at all.)

At the same time, like I said, I can understand that there are cases when you would like to turn off the attribution, and technically it would not be so hard.

One solution would be to add a new property on the `ms` object called `attribution` that by default would be set to `true`, and then https://github.com/spatialillusions/milsymbol/blob/master/src/ms.js#L55
could be updated to
```js
if (typeof console === "object" && this.attribution) {
```
and information about setting this property would also have to be added to the documentation. 
(*The documentation should also contain information that you should only set ms.attribution to false if you have given attribution according to the license in another part of your application or documentation.*)

If you could provide a Pull Request I could merge it into the code.

**Comment by jziggas** [comment]
I always understood MIT's attribution to mean including the license and its attribution within the source. There are [several](https://softwareengineering.stackexchange.com/a/218338/197057) [stack exchange](https://opensource.stackexchange.com/a/4061) discussions that seem to reflect this.

Anyway, your work is definitely appreciated from at least one defense system!

**Comment by spatialillusions** [comment]
Just make sure that you don't minify away the license text in the source code when you build your web app. (I have done this by my self.) And if you do build your web app and minify away all comments, then you would need to have an about box with the license text in the same way as if you distributed a binary. (At least this is how I have interpreted the license.) https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html

And if you are able to tell me more about what defense system and maybe provide a screenshot or similar I'm always interested. **hint hint** My email adress can be found on the homepage.

**Comment by spatialillusions** [comment]
Just realized, the simplest way to do this, is to simply clear the console after milsymbol is loaded. But of course, I prefer if the attribution is kept in place.

Sort of like this:
```js
import ms from "milsymbol";
console.clear();
```

**Comment by dougajmcdonald** [comment]
I'd like to second this request as any unit tests we have which test files that `import ms` subsequently output the attribution to the console.

This causes a lot of noise and can cause some CI's to fail if they are strict about console usage.
