### ISSUE TITLE
Grouping Symbol Parts within SVG <g> elements

### ISSUE THREAD

**Issue by MattShawPhoto** [spatialillusions/milsymbol#134]
Hi @spatialillusions 

I'm looking at the example at https://spatialillusions.com/demos/groupmarker/index.html each symbol part has it's own <g> element that encloses it I.E:

```
<g id="symbolModifier">">...</g> 
<g id="BaseGeometry">...</g> 
<g id="StatusGeometry">...</g> 
<g id="AffliationDimensionGeometry">...</g> 
<g id="Icon">...</g>
<g id="texts">...</g>
etc
```

![mil symbol groups](https://user-images.githubusercontent.com/1172174/30483376-a9c9aed2-9a1e-11e7-959e-436447863e96.PNG)

This is useful because it will allow the bounding boxes (and the centers thereof) of these elements to be calculated or retrieved using various query selectors (getElementById, getElementByClassName, etc) which can be useful if it is necessary to position an element for example relative to the the cx/cy of the icon component (a range circle for example whose center is at the center of the icon, rather than the bbox of the whole symbol) of a symbol or if one wishes to control the visibility of the text amplifiers (or other parts).

The example at the URL above uses v0.4.5; The current version (v1.3.0) does not do this and the elements that comprise a symbol instance are direct descendents of the parent <SVG> element. 

Are there any plans to reintroduce the grouping of symbol parts within <g> elements or if not; is there a way of retrieving the center point for the icon part of the symbol ?

**Comment by spatialillusions** [comment]
The center of the icon (octagon center) is always in 100,100, because of legacy reasons, and you don't have to know the scale of the symbol when you add custom elements. This together with the symbol bounding box should give you all the information you need. 
Custom elements can be added anywhere in the order and the elements can be drawn on top of the symbol or below. 

I think this should provide you with all the information you need, if so please close the case, otherwise add more information of what you would need.

**Comment by MattShawPhoto** [comment]
That the centre of the octagon is essentially a constant actually helps massivey and is what I was looking for. I think I might have actually seen a reference to this in the docs somewhere but didn't quite make the connection. Thanks for such a quick reply.
