### ISSUE TITLE
following code always returns unframed circle for code?

### ISSUE THREAD

**Issue by ssdhaliwal** [spatialillusions/milsymbol#135]
Just checking, may be I am doing something wrong.  Below code returns a circle with purple color icon vice framed icon for surface vessel?

SFSPXMP---*****
SFSPXL----*****
new ms.Symbol(symbol, {"size":symSize, "direction":symDirection, "frame":true}).asSVG();

All the Sea.Surface.Track.NonMilitary? is there a way to force MILSTD2525BC2 as output?

**Comment by spatialillusions** [comment]
What I think you want to do, even if your question is a bit unclear, is to not use civilian colors for civilian vessels. 
This is described under:
https://github.com/spatialillusions/milsymbol/tree/master/docs#mssymbolarg1-arg2--argn

So this should give you the output you want:
´´´
new ms.Symbol(symbol, {"size":symSize, "direction":symDirection, "frame":true, "civilianColor":false}).asSVG();
´´´

If you don't want the frame around the symbol and simply a colored boat icon, simply set frame to false. 

If this solves your problem, please close this case, otherwise could you please provide a more detailed description of what output you expect.

**Comment by ssdhaliwal** [comment]
Thank you - that worked like a charm.
