### ISSUE TITLE
Issue with Edge

### ISSUE THREAD

**Issue by tacticalguy** [spatialillusions/milsymbol#136]
First Off I would like to thank you for the wonderful job you have done on the library.  

Now to the question at hand....
Is anyone having issues with Edge?  I am able to display everything but the image itself.  I noticed that both  you Cesium and ArcGIS examples are also exhibiting the same issue while running in the edge browser(They work with IE)

https://spatialillusions.com/demos/arcgis3d/index.html
https://spatialillusions.com/Demos/cesium/

Any help is greatly appreciated.
Thank you!

**Comment by kjellmf** [comment]
I'm having the same issue in Edge. Only affects examples that use Canvas. Trows a lot of the following error message:
 ```
2DCONTEXT20301: Attempt to construct Path2D from unsupported type. Empty path created.
```
Maybe related to this Edge issue? https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8438884/

**Comment by spatialillusions** [comment]
Thanks for pointing this out, and we should be able to solve this quite easy. If would however be appreciated if someone could help me out since I don't have Edge on my main development computer.

The problem seems to be that Path2D is available in Edge, but it can't take an svg path as input.
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8438884/

In milsymbol I check if Path2D is present and if not I use my own replacement function that is a bit slower but works. This is done at this place in the code:
https://github.com/spatialillusions/milsymbol/blob/master/src/symbol/ascanvas.js#L45

So either the if statement should be something more clever, or we should use a try-catch to catch the error. (Might be good to do some code refactoring there as well...)

Pull requests are as usual always welcome, otherwise I will try to fix it as soon as possible.

**Comment by spatialillusions** [comment]
I have made a solution that should fix this, but it would be great if someone else could build milsymbol and try it out by running the canvas speed test demo or something else that makes milsymbol render canvas images in Edge. Found out that my windows computer still uses an older version of Edge, and I can't update to a new version because of company rules.

**Comment by kjellmf** [comment]
I will test it out later today.

**Comment by spatialillusions** [comment]
Now been able to verify that my fix does not work. Need to look more into this.

**Comment by spatialillusions** [comment]
Ok, so this is quite tricky. In EdgeHTML14 Microsoft implemented support for Path2D, but they didn't implement support for initiating it with a SVG path, and if you initiate it with an SVG path, it will not throw an error, instead it will return an empty path and log a warning. 
This makes it hard to catch when there is an error, and we don't want to force Edge to always use the workaround for older versions of IE and Edge that is built into milsymbol since Microsoft hopefully will fix this in the future. 
So any workarounds that will solve this is welcome, because at the moment I'm sort of stuck...

**Comment by kjellmf** [comment]
I've experimented a bit with Path2D in Edge and came to the same conclusion as you @spatialillusions . I have not found any workarounds yet.

**Comment by tacticalguy** [comment]
Wow !!!  Just getting back to work. Thanks to everyone for all your efforts.   I will think about some possibilities and also work with Microsoft to find out when, if at all, the fix is in their pipeline.  

Thank you again!

**Comment by spatialillusions** [comment]
I have submitted a patch that will check if Path2D is broken and if so use the work around. Would be much appreciated if someone could build the code and test it out in different web browsers to make sure that I didn't break anything. It might also be good to check what the result of toDataURL is in different browsers so that we don't use the workaround when it isn't needed, I have only tested in Edge and Chrome so far.

**Comment by spatialillusions** [comment]
Just published milsymbol 1.3.1 that contains a fix for this. (Or at least I think that this should fix everything.) Please let me know if you run into any further problems.

**Comment by spatialillusions** [comment]
@tacticalguy Could you close this case when you have verified if 1.3.1 solves your problems?

**Comment by tacticalguy** [comment]
Amazing Job!  Just got a chance to test and it seems to work perfectly.

Thank you again for your support.

**Comment by spatialillusions** [comment]
FYI, I have now updated the samples for ArcGIS 3d, Cesium and Mapbox on spatialillusions.com to use the new 1.3.1 release so that they work in Edge as well. 
And @tacticalguy if you are able to tell me more about the project you are working on, please send me an email, you can find my contact details on spatialillusions.com.
