### ISSUE TITLE
Openlayers example does not work in IE11

### ISSUE THREAD

**Issue by kjellmf** [spatialillusions/milsymbol#15]
I noticed that the OpenLayers example at http://spatialillusions.github.io/MilSymbol/examples/openlayers3/index.html does not work in IE11. When I open the debug console the following error is shown multiple times:

`XML5634: An attribute with the same name already exists on this element. Line: 1, Column 155`

Any idea why it don't work?

**Comment by kjellmf** [comment]
The issue seems to be that the SVG generated by MilSymbol contains two xmlns attributes. If I comment out the following lines I get rid of the XML5634 error
https://github.com/spatialillusions/MilSymbol/blob/master/bin/MilSymbol.js#L6641
https://github.com/spatialillusions/MilSymbol/blob/master/bin/MilSymbol.js#L6912

`if(_MilSymbol.userAgentIE){svgSymbol.setAttribute("xmlns", svgNS)};`

Unfortunately it looks like the example then runs into a bug in openlayers and I'm still not able to render the example in IE11. I get several `IndexSizeErrors` exceptions. I found a couple of OL-issues may be related: 
https://github.com/openlayers/ol3/issues/3220
https://github.com/openlayers/ol3/issues/2861

**Comment by spatialillusions** [comment]
Ok, the first about the double xmlns is a dirty fix for older versions ie than 11. They shouldn't, but require it to be written twice.... So that needs obviously to be fixed with a check of the version number of ie, so that it's not applied to ie11. 

For the open layers issues, have you tried to change the open layer version to the latest, 3.4.0?

/Måns

**Comment by kjellmf** [comment]
I have tried 3.4.0 and got the same error. I have not tried the master branch version yet. Will do.

**Comment by kjellmf** [comment]
Another related ol3 issue/pull request. 
https://github.com/openlayers/ol3/pull/2846

This is clearly a bug in OL, so there is not much you can do in MilSymbol. If I don't find a solution soon I will probably switch to Leaflet.

**Comment by kjellmf** [comment]
I found a workaround for the canvas issue!

I changed the following code:

```javascript
mysymbol[i] = new MilSymbol(Units[i].SIDC,{size:iconSize[(Units[i].SIDC).charAt(11)]}).symbolMarker()
 
myicon[i] = new ol.style.Style({
	image: new ol.style.Icon(/** @type {olx.style.IconOptions} */ ({
		anchor: [mysymbol[i].x, mysymbol[i].y],
		anchorXUnits: 'pixels',
		anchorYUnits: 'pixels',
		src:  "data:image/svg+xml;base64," + btoa(mysymbol[i].textXML)
	}))
});
```
to 
```javascript
mysymbol[i] = new MilSymbol(Units[i].SIDC,{size:iconSize[(Units[i].SIDC).charAt(11)]}).symbolMarker();
var svgImage = new Image();
svgImage.src = "data:image/svg+xml;base64," + btoa(mysymbol[i].textXML);
myicon[i] = new ol.style.Style({
	image: new ol.style.Icon(/** @type {olx.style.IconOptions} */ ({
		anchor: [mysymbol[i].x, mysymbol[i].y],
		anchorXUnits: 'pixels',
		anchorYUnits: 'pixels',
    img: svgImage,
    size: [mysymbol[i].width, mysymbol[i].height]
	}))
});
```
Now the example renders in IE11 (after I commented out the useragent check).

**Comment by kjellmf** [comment]
My pull request (#16) fixes the rendering issues in IE11, but unfortunately I ran into more IE11 canvas security issues. Now it is triggered when OL3 does hit detection (needed for dragging and selecting the symbols). A workaround that probably will work is to use [`Ol.Overlay`](http://openlayers.org/en/v3.5.0/apidoc/ol.Overlay.html) instead of `ol.style.Icon`. This will render the symbol as DOM object (as Leflet does).  I have not tried this yet though.

**Comment by spatialillusions** [comment]
At the moment my time and Internet access is limited, and the only computer I can do development on is a Mac, but hopefully I'll be able to look into the ie/open layers stuff in about a month. The reason that style.icon and not overlay was used from the beginning is that it wasn't available in open layers when the demo was written.

**Comment by spatialillusions** [comment]
This is fixed in milsymbol 0.5, now in development.

**Comment by aascasibar** [comment]
Hi,
First of all, thank you for this awesome library. It is really useful.
I know that this fork is closed but I still experienced problems with the symbols when I try to get the features in OL3 with the "singleclick" event. Just in case someone is stack in this point, I fix it converting  the svg symbols to canvas using canvg.

Thanks
Alex

**Comment by kjellmf** [comment]
@aascasibar I ran into the same issue earlier this year. I was not able to find a workaround then, so I switched to Leaflet. I have not revisited the issue with the latest versions of OL3. Good to know that canvg is an option.

**Comment by spatialillusions** [comment]
Are you using milsymbol 0.5 or earlier? If you haven't upgraded to 0.5 and you are using IE you should really do so, because there is a huge speed improvement. I'm not able to test on my windows laptop at the moment, but I did a web best IE 11 test of this page http://spatialillusions.com/milsymbol/examples/openlayers3/imageicons.html and everything looked fine. 

Please let me know if you have any further problems. 

/Måns

**Comment by spatialillusions** [comment]
Just checked with my windows computer and everything works fine in IE11 in version 0.5, if you need help converting old code the new API, just send me an email and I can guide you to how to do it. I updated all my old examples quite quickly.

**Comment by kjellmf** [comment]
The problem is not the new version of MilSymbol, The example works fine in IE11, but if you try to expand the example and add a click handler or drag hander, you'll run into a security warning in IE11. It could be that they have fixed this in the latest version of Ol3. I'll take a look when I have some spare time.

**Comment by spatialillusions** [comment]
I think this is the reason:
http://svgopen.org/2010/papers/62-From_SVG_to_Canvas_and_Back/#security_issues
IE11 can't tell the difference between safe and unsafe SVG, not sure if this can be solved in openlayers 3 without major changes.

**Comment by aascasibar** [comment]
Thank you very much for your support.... Indeed the problem is in the IE11 because FF and Chrome works fine.

I have bad news regarding canvg... after interacting with OL3 for a while the memory of the iexplorer process increase dramatically up to 1.5  Gb and then the browser crashes.
Sadly, I didn't find the way to make milsymbol work in IE11 :-(. 

If I have a bit of time, maybe I can have a look to your library (if you dont mind) and try to create the symbols in Canvas instead of SVG.

**Comment by kjellmf** [comment]
@aascasibar Have you tried to use an ol.Overlay instead? Examples: http://openlayers.org/en/v3.9.0/examples/overlay.html?q=overlay  http://www.acuriousanimal.com/thebookofopenlayers3/chapter06_02_markers_overlays.html

Should work with milsymbol, but I have not experimented with this.

**Comment by spatialillusions** [comment]
@aascasibar Feel free to branch and edit the library in any way you want. Since it uses a BSD license it is up to you if you want to release the modified code or not, but of course it's nice if you do.

Like @kjellmf says it should work if you use overlays in open layers. The other solutions you got is to switch to LeafLet, or draw the symbols on a d3 overlay on top of your open layers map http://openlayers.org/en/v3.9.0/examples/d3.html

milsymbol as such works fine with IE11, and drawing them to the canvas also works fine, but it is drawing SVG to canvas and then requesting the canvas data that causes a security error in IE11. This is because IE11 can tell the difference between SVG with foreign objects and SVG only containing native geometries, and because of this marks the canvas as "tainted" to prevent data reading. I spent some time today to see if it can be fixed in open layers, but unfortunately it dosen't look like that until they support vector layers on other renderers than canvas, and there dosen't seem to be a plan for that... 
There might be a solution to use a proxy layer in open layers, where you draw almost transparent squares covering the icons and when they are moved you update the symbol layer, but I'm not sure if it might work.

**Comment by spatialillusions** [comment]
I made a pull to open layers that should solve this. @aascasibar you can have a look at openlayers/ol3#4090

**Comment by kjellmf** [comment]
@spatialillusions I tested this in IE Edge (windows 10) and it worked fine. Looks like this is only an issue in IE11 and lower. 

I'm following your pull request on the OL3 project. Great work! Looks like it will be merged too.

**Comment by spatialillusions** [comment]
My pull got merged into openlayers, so this will be fixed in the next version.

**Comment by carlocarlini** [comment]
i was not able to let a single example work on my pc about OpenLayers 6.
a small example of how to test them is appreciated or some precaution.
I want to switch to OpenLayers from Google Maps but i find OpenLayers very complicate and taking too much coding

**Comment by spatialillusions** [comment]
If I find time to update the examples to Open Layers 6, I will do so. Otherwise it is always welcomed with a pull request that updates the current examples.
