### ISSUE TITLE
Version 2.0.0 release

### ISSUE THREAD

**Issue by adamsteinbok** [spatialillusions/milsymbol#194]
Hello,

The logged version of milsymbol.js on https://spatialillusions.com/unitgenerator/ is 2.0.0, however there is no corresponding release 2.0.0 for this repo. 

When can we expect a new release?

Thanks

**Comment by spatialillusions** [comment]
I'm waiting for MIL-STD-2525D change 1, that was supposed to have been released quite some time ago. Since milsymbol 2.0 includes parts of the draft specification, I will have to wait for the final release before releasing a new version of milsymbol. After the final release has been done of the standard, I will have to make sure that I render all symbols correctly if they have done any changes after the draft I got, this should however not be that much work, and the standard is said to be released quite soon. 
If you want to try out the next version of milsymbol, you can do `npm -i milsymbol@next` to install the RC from NPM.

**Comment by adamsteinbok** [comment]
Thanks. Your advice to use milsymbol@next worked.
