### ISSUE TITLE
2525d Control Measure outline not displayed without explicitly setting monoColor

### ISSUE THREAD

**Issue by adamsteinbok** [spatialillusions/milsymbol#195]
Outlines for the 'new' 2525d Control Measure symbol set are not displayed unless the monoColor parameter is explicitly set. Ideally the outline being displayed would be decoupled from the color of the symbol.

**Comment by spatialillusions** [comment]
This is a very good find that I missed in my testing, it should now be fixed with my last commit. It didn't really have anything with the color to do and it could be "fixed" by setting the symbol fill to false, but now the code will do it in a better way and automatic, it also fixes the outline for some sea mines where it didn't work before.

**Comment by adamsteinbok** [comment]
Thanks for the fix. That was an impressive response time. 

What's your RC release process like? Just so I know when to expect this to propagate to @next in npm.

**Comment by spatialillusions** [comment]
Sorry for the delay, I was at the gym. ;-)
You should now be able to grab rc3 from npm using @next.
