### ISSUE TITLE
letter() is not present

### ISSUE THREAD

**Issue by Laser11** [spatialillusions/milsymbol#215]
I'm trying to test implementing the plugin on an offline PC for Cesium, but I keep catching a runtime error saying ms._getMetadata.letter() on getmetadata.js, and ms._getIcons.letter() on icon.js are not present, and that I "need to load functionality for letter based SIDCs. Am I missing a file? Is the issue caused by attempting to implement it without an online connection?

**Comment by spatialillusions** [comment]
Do you have Cesium up and running on your offline PC without milsymbol? I'm asking because before it was hard to run Cesium without a server. 
Otherwise it sounds like you are loading milsymbol as an ES6 module, that can cause it not to load all features (this is a feature not a bug). 

If you are loading index.esm.js then try to load index.js instead and things should work if you have a browser that supports ES6 modules from local files, but that could be a problem. 

Have a look at https://github.com/spatialillusions/milsymbol/blob/master/examples/es6-import/index.html for how to load parts of milsymbol, or build milsymbol and load the built file in the dist folder. You can also grab a fairly new build from https://spatialillusions.com/milsymbol-dev/dist/milsymbol.js
