### ISSUE TITLE
APP6D. Control measure. H1, T1 texts

### ISSUE THREAD

**Issue by zizizuq** [spatialillusions/milsymbol#216]
Could you add possibility for customize texts H1, T1 for Control measure icons
![image](https://user-images.githubusercontent.com/45353847/49137350-ddaf5f00-f2f4-11e8-839b-7cd6b7756200.png)
![image](https://user-images.githubusercontent.com/45353847/49138169-2c5df880-f2f7-11e8-9cbb-992b34ffb9fb.png)
![image](https://user-images.githubusercontent.com/45353847/49138077-f3be1f00-f2f6-11e8-8db9-06a96fb5f334.png)

**Comment by spatialillusions** [comment]
Milsymbol do support the T1/H1 fields, as you can see here:
https://spatialillusions.com/milsymbol-dev/docs/milsymbol-APP6d.html#heading-52
I have however not added input fields for them in the unit generator, because I thought it would confuse more than it would be of use. 
The source code for the unit generator can be found here:
https://github.com/spatialillusions/milsymbol-generator
You can either add the input field to the code by your self, or I can do it on a consultancy basis, please contact me via email if you would be interested in that.
