### ISSUE TITLE
Inconsistent label sizes for some point symbols

### ISSUE THREAD

**Issue by dehmer** [spatialillusions/milsymbol#230]
Is it on purpose that some point symbols have different font sizes for unique designation (T), 'XXX' in the examples below?

<img width="417" alt="Screen Shot 2019-09-16 at 15 48 45" src="https://user-images.githubusercontent.com/322462/64963625-dcf2b400-d899-11e9-9ed4-8699d6f994e6.png">

I know there are examples in MIL-STD-2525C which suggest this label to be bigger sometimes, but I believe that's just mild carelessness of the spec.

<img width="500" alt="Screen Shot 2019-09-16 at 15 44 55" src="https://user-images.githubusercontent.com/322462/64964226-e92b4100-d89a-11e9-9822-86631260a4e8.png">

Either there is a reason for that or I would like to have the same font size for modifiers around symbols. Preferably the smaller/default size like in 'G*SPPSZ---****X'.

**Comment by spatialillusions** [comment]
This is a bit tricky. Like you say this was done in this way because it looked that way in 2525C, and I liked the look of it, and then they way that they show it in 2525D is quite ugly. I can double check with the SSMC what they think. It is possible to change this with a custom label function, just replace https://github.com/spatialillusions/milsymbol/blob/master/src/numbersidc/labels/tactical-points.js. I will keep it they way it is for now, and then I'm going to keep this in mind for the next major of milsymbol.
