### ISSUE TITLE
Ideas for a validation function

### ISSUE THREAD

**Issue by amarant** [spatialillusions/milsymbol#24]
In accordance to the issue #21 here is some ideas about validation of the SIDC :
- number of letters : to few, to much, for example APP6B is 15.
- value of categories : some categories have a fixed number of possibilities, for APP6B position 2 is affiliation from a limited number of letters, function ID from 5 to 10 values are in the standard, country code 13 and 14 ...

Thanks.

**Comment by gmoyanollc** [comment]
The MIL-STD-2525 spec should be encoded for computer consumption, for example, in XML XSD and Schematron, so that conformance can be tested.  Testing conformance provides a higher level of confidence that a symbol will communicate the intended information for life or death situations.

**Comment by spatialillusions** [comment]
Issues with the MIL-STD-2525 standard is better to post at https://github.com/Esri/joint-military-symbology-xml/issues since I know that the standard management checks there for issues. (And we talked at the last meeting that it would be great to have a separate issue tracker for the standard, so things don't get mixed up with the esri implementation.)

**Comment by spatialillusions** [comment]
My idea at the moment is to create a tree structure of all data, and that could be used to validate SIDCs.

**Comment by spatialillusions** [comment]
I uploaded a lot of raw standard data to the dev folder. Will keep on structuring the data to make a validation function, it's still work in progress.

**Comment by spatialillusions** [comment]
@amarant Would it be sufficient if I checked if I was able to find an icon for the sidc? Or is there other things you would like to validate?

**Comment by spatialillusions** [comment]
I have now added a method that checks if it was possible to get an icon for the given SIDC, this will return `false` if no icon was found and an upside down question mark will be drawn as the icon instead. When it comes to validate other properties, this would require quite a lot of work, because of how milsymbol is built and basically tries to handle all input and parse it as good as possible. And because of how the standards are defined, a tactical point without affiliation might not be wrong, it's just missing affiliation.

If more validation is needed, please open a new case for each property that should be validated, or even better, provide a pull request for each property.
