### ISSUE TITLE
App6D - installation amplifier not exists for Land Unit

### ISSUE THREAD

**Issue by yuvDevIndepth** [spatialillusions/milsymbol#242]
Hi,
According to milsymbol docs (https://www.spatialillusions.com/milsymbol/docs/milsymbol-APP6d.html#heading-14)  Figure 3-3: Land Unit and Civilian Organization Symbol Amplifier Fields not contains the installation amplifier. (see pic below)
![image](https://user-images.githubusercontent.com/58777235/70625022-37e24000-1c2a-11ea-90c9-31881f610b3a.png)

But according to the APP6D standard it does suppose to the installation amplifier (see pic below)
![image](https://user-images.githubusercontent.com/58777235/70624962-1c773500-1c2a-11ea-98a0-289c8c8e2b01.png)
Can you please help with this issue?

Thanks.

**Comment by spatialillusions** [comment]
This is a bit tricky, since you are correct that this is mentioned in the standard, but there is no way in the standard to set the installation modifier on other symbols. I guess it could be a custom property ,but that would be sort of strange... Not sure what to do here, I will pass the information to the SMC that there is something strange in the standard.
