### ISSUE TITLE
Support in APP-6A

### ISSUE THREAD

**Issue by YahavTheKing123** [spatialillusions/milsymbol#248]
Hello Mans,

I would like to know if your library supports also APP-6A standard.
If not, can you estimate what is need to be add/change in order it to be supported?

I randomly tried some APP-6A sidc's and it seems to be paint according to the standard...

Thanks for your replay!

**Comment by spatialillusions** [comment]
Most of the SIDC codes should work with APP-6 A, but I have not tested them, and I have not extracted the codes from the standard so that it is possible to do so. If you want to check what codes that works, you have to test them one by one manually, or extend some of the tests to test them. There are no plans to add support for APP-6 A to milsymbol, since this is a very old standard.
