### ISSUE TITLE
Where is the definition for letterbased sidc?

### ISSUE THREAD

**Issue by eulenleber** [spatialillusions/milsymbol#276]
https://litpolukrbrig.wp.mil.pl/u/APP-6D_JOINT_MILITARY_SYMBOLOGY._16_October_2017.pdf

thats the APP 6D which contains only some number based sidcs

Background of the question is:
I need to introduce a new set of symbols for non-military purposes and need to introduce new sidcs (as well as echelons btw) ; but it seems that the lib relies on the "correct" sidcs - so, is there any documentation about these letter based sidcs?

regarding the echelons - there is an Echelon defined between Platoon and Company (basically 4 circles, like two squads next to each other) - its not implemented so far (?)

**Comment by dehmer** [comment]
Disclaimer: I'm not an author of milsymbol and only give information I THINK is true.

Letter/alpha (15-char) SIDCs are defined in APP6C or MIL-STD 2525C (or older).

I'm not too familiar with milsymbol extension mechanism, but I can imagine that is quite hard to invent new SIDCs since a SIDC carries quite some semantics. I guess introducing new coding schemes or (battle) dimensions will lead nowhere, because they are simply not handled. But I can be wrong about this. Messing with existing coding schemes/dimension may produce unexpected results, since ranges of function ids are tested for specific meanings or requirements for different styling.

Introducing new Echelon will most probably not work. Even though only '-A' (team) up to '-N' (command) are taken, the SVG draw instructions are hard coded and cannot be extended.

Saying that, I'm currently playing with the idea to rewrite milsymbol to easily provide the possibility to add/register new symology standards only from (static) configuration files. Our software has quite some demand for additional/different 1-point symbols. I have some basic code working, but completely migrating APP6 C/D and 2525 B/C/D from milsymbol would be pretty demanding (but probably possible.)

**Comment by spatialillusions** [comment]
You can find the letter based SIDC specification here, just download MIL-STD-2525C:

http://everyspec.com/MIL-STD/MIL-STD-2000-2999/MIL-STD-2525C_20429/

You can also find all the information extracted here:

https://github.com/spatialillusions/mil-std-2525


And for APP6 you can find the extracted information here:

https://github.com/spatialillusions/stanag-app6


When it comes to extending milsymbol, it is built very modular, and almost everything can be changed or updated. I once made a sample here: (Yes it is possible to change the symbol parts.)

https://twitter.com/spatialillusion/status/939891636951240704?s=61&t=PuGpHMa1duQrcvAxl6r5yg

<img width="553" alt="image" src="https://user-images.githubusercontent.com/8155542/211629988-f0acc51a-1ef2-470a-adb9-1e6b136388a0.png">

<img width="302" alt="image" src="https://user-images.githubusercontent.com/8155542/211630079-feb21244-bebb-4cd8-bb08-ac7b861aecad.png">
