### ISSUE TITLE
Wheeled  modifier overlaps infantry icon

### ISSUE THREAD

**Issue by kjellmf** [spatialillusions/milsymbol#277]
The spacing between the circles in the wheeled sector 2 modifier is slightly off. For the infantry icon this results in the circles overlapping the diagonal lines as shown in the symbol below:

![image](https://user-images.githubusercontent.com/29217/212496605-e51e4654-0ec4-41b0-a3ce-006f7c391f32.png)

The icon part is defined here:
https://github.com/spatialillusions/milsymbol/blob/1c17e57282f505fb9ebcd42e04ef2ab1e1b102e6/src/iconparts/ground.js#L1954
and used here:
https://github.com/spatialillusions/milsymbol/blob/1c17e57282f505fb9ebcd42e04ef2ab1e1b102e6/src/numbersidc/sidc/landunit.js#L574
It is also used a few other places as well:
https://github.com/spatialillusions/milsymbol/search?q=%22GR.M2.WHEELED%22

One possible fix is to modify the GR.M2.WHEELED icon part definition, but this may break other symbols because the icon part is used multiple places.

**Comment by spatialillusions** [comment]
I will look into this, I agree that it should be changed. (Should be a bit bigger as well in my opinion...)

**Comment by spatialillusions** [comment]
Some parts of milsymbol are still based on my initial work 10 years ago, and the assumptions I did then. I have now reconsidered a bunch of stuff, and have planned to start a major refactoring of how symbols are created. (When I find the time.) First I just have to get a bit further on the new symbol generator so that I don't have multiple projects at once.

I'll keep you posted.

**Comment by spatialillusions** [comment]
Should be fixed in current codebase and upcoming 3.0.
