### ISSUE TITLE
Offer Minified Version

### ISSUE THREAD

**Issue by okwolf** [spatialillusions/milsymbol#45]
Would it be possible to also offer a milsymbol.min.js as many other JavaScript libraries offer for saving space when distributing for production use? You can use UglifyJS or whatever method works easiest for your build. Please keep the milsymbol.js version for use during development however.

**Comment by spatialillusions** [comment]
i did some experiments using ugilifyjs to minify milsymbol, but the size change was marginal. I have however been thinking about creating a minified version, so I'll keep it in mind to the next release.

**Comment by okwolf** [comment]
We can always run minification on our concatenated JavaScript ourselves. I was merely curious if you plan to offer one that's already been minified.

**Comment by spatialillusions** [comment]
I have been looking into it and like I said before the reduction in size won't be so much, so that's simply why I havn't started making a minified version. 

However, what has been on my long to do list for quite some time is to convert the icon parts object with named keys into a simple numbered array. If all name strings in milsymbol is replaced by a numerical index the size reduction could be quite a bit. I was thinking about this at the same time as I reduced the precision on all coordinate geometries and reduced the library quite a lot in size. 

I will keep this issue open and we'll see if I'm able to find some time to fix this.

**Comment by spatialillusions** [comment]
I'm looking into #9 and adding build scripts will make it possible to create a minified version at the same time as combining the sources. All input on simplest/best way to make a build script for milsymbol is welcome.

**Comment by okwolf** [comment]
Thanks! I added my thoughts to #9, since they're broader than what this issue captures.

**Comment by spatialillusions** [comment]
At the moment my idea is that once the webpack build of milsymbol is working as it should, the default milsymbol.js will be minified, and then there might be a milsymbol-debug.js that isn't minified.

**Comment by spatialillusions** [comment]
With the new webpack packaging the minified version will be the default version included.
