### ISSUE TITLE
Control colors using CSS.

### ISSUE THREAD

**Issue by robross0606** [spatialillusions/milsymbol#48]
Would be good if colors were expressed as a CSS file which could then be modified if necessary.

**Comment by spatialillusions** [comment]
In milsymbol colors are modified using color modes containing color objects. 
http://spatialillusions.com/milsymbol/docs/index.html#colorobject
This gives you a flexible way to modify all colors using code, and it works with both SVG and Canvas output.
Is it something you want to do that isn't possible using the current methods for modifying colors?

**Comment by spatialillusions** [comment]
Since there hasn't been any more feedback on this issue, I'm closing it. Re open if there is a specific case for changing colors using CSS instead of the API.

**Comment by robross0606** [comment]
The purpose of CSS in general is to maintain separation between code and design.  Sometimes designers need adjust design but don't know too code.  Often there is even secure separation.  Saying that CSS isn't necessary because you can "do it in code" is missing the entire point if CSS.

**Comment by spatialillusions** [comment]
I understand your point, and if you figure out a good way to handle colors from CSS I would consider to add the functionality. What I would suggest is a function that reads colors from the CSS and if some kind of values are specified it will call `MS.setColorMode('colormodename',<Color object>)` to modify one of the predefined color modes. To get colors from a CSS is however a bit tricky, but maybe something like here:
http://stackoverflow.com/questions/16965515/how-to-get-a-style-attribute-from-a-css-class-by-javascript-jquery

Then there is the thing that you shouldn't change the colors from the standard specification if you don't absolutely have to, because then they won't follow the standard any more.

**Comment by spatialillusions** [comment]
@robross0606 Could you provide an example of what colors you want to change, and why?
I have been thinking about this and I actually think it is a good thing that it is "hard" to change the colors, since changing the colors will create symbols that won't follow the standards. I also think it is functionality that would be better in a milsymbol-extension than in the base library, but you might have a use case that I haven't thought about.

**Comment by spatialillusions** [comment]
One quick solution, that isn't CSS, but quite close, is to save this code as milsymbol.colors.js, and load it directly after you load milsymbol.
```
MS.setColorMode('Light',{
	Hostile:	"rgb(255,128,128)",
	Friend:		"rgb(128,224,255)",
	Neutral:	"rgb(170,255,170)",
	Unknown:	"rgb(255,255,128)",
	Civilian:	"rgb(255,161,255)"
});
```

**Comment by spatialillusions** [comment]
I have decided that this functionality will not be a part of milsymbol, but it could be an extension, I will however not prioritize to write the code at the moment.
