### ISSUE TITLE
adding a change log

### ISSUE THREAD

**Issue by workingDog** [spatialillusions/milsymbol#55]
I'm trying to keep my scala interface to milsymbol.js up to date.
To do this it would be of great help to have a change log 
(e.g https://github.com/workingDog/ScalaMS/blob/master/CHANGES.md) to record what has changed in 
what version.

**Comment by spatialillusions** [comment]
I have added a changelog now. I also saw that since you have implemented the new toDataURL() method I'm guessing that you are using the master branch for your development. Just be aware that the master branch can be unstable since that is where I do most my development. I try to not make any breaking commits, but you can never be totally sure.
