### ISSUE TITLE
Update icon for field artillery single/multiple rocket self-propelled

### ISSUE THREAD

**Issue by FlemmingJ** [spatialillusions/milsymbol#71]
Accoding to MIL-STD-2525C 2008, the icon for "WARFIGHTING SYMBOLS/GROUND TRACK/UNIT/COMBAT/FIELD ARTILLERY/ROCKET/SINGLE ROCKET LAUNCHER/SINGLE ROCKET SELF-PROPELLED" should have the ^'s over the dot inside the rounded rectangle.
From http://www.spatialillusions.com/milsymbol/docs/milsymbol-2525c-svg.html#TABLEV
![image](https://cloud.githubusercontent.com/assets/25221825/22103645/3edd01f8-de3c-11e6-9db1-6afc77c034a0.png)

Icon on page 137 in the MIL-STD-2525C:
![image](https://cloud.githubusercontent.com/assets/25221825/22103327/0416f3cc-de3b-11e6-9f00-3c0aaf3e8fde.png)

This applies to both the single and the multiple rocket version, when they are self-propelled:
WAR.GRDTRK.UNT.CBT.FLDART.ROC.SRL.SRSP Hierarchy: 1.X.3.1.1.7.2.1.1 SFGPUCFRSS*****
WAR.GRDTRK.UNT.CBT.FLDART.ROC.MRL.MRSPD Hierarchy: 1.X.3.1.1.7.2.2.1 SFGPUCFRMS*****

**Comment by spatialillusions** [comment]
In this case the MIL-STD-2525D symbology for the same symbol is used, in my opinion this is a clearer representation of this symbol and follows a more logical building pattern. Since the icon definitions in milsymbol are shared between standards to reduce size of the library symbol definitions has been reused in all cases where there isn't major differences between the standards.
This also follows how the symbols are drawn in ADRP 1-02.

Because of this, I won't update this symbol at the moment. However, if this is very importent for you or your customer, there is ways to modify specific symbols in milsymbol and I could provide you with instructions for how to modify the symbols using a small override that you can include in your milsymbol build.

**Comment by FlemmingJ** [comment]
Thx for the quick answer. 
Our customers have not yet noted the difference. If they do and wants to have it changed, I'll get back to you about how to modify it locally.
