### ISSUE TITLE
drawInstructions is undefined

### ISSUE THREAD

**Issue by gonzofish** [spatialillusions/milsymbol#75]
First off, nice library!

If I run the following:

```javascript
var symbol = new MS.symbol("sfgpewrh--mt", {
    size: 35,
    quantity: 200,
    staffComments: "for reinforcements".toUpperCase(),
    additionalInformation: "added support for JJ".toUpperCase(),
    direction: (750*360/6400),
    type: "machine gun".toUpperCase(),
    dtg: "30140000ZSEP97",
    location: "0900000.0E570306.0N"
});

console.info(symbol.asSVG());
```

My browser is error out with:

```shell
TypeError: Cannot read property 'length' of undefined
```

I tracked it down to the `drawInstructions` in `asSVG` not be defined. I noticed that `drawInstructions` gets defined in `getMarker()`. So when I run:

```javascript
var symbol = new MS.symbol("sfgpewrh--mt", {
    size: 35,
    quantity: 200,
    staffComments: "for reinforcements".toUpperCase(),
    additionalInformation: "added support for JJ".toUpperCase(),
    direction: (750*360/6400),
    type: "machine gun".toUpperCase(),
    dtg: "30140000ZSEP97",
    location: "0900000.0E570306.0N"
});

// added line
symbol.getMarker();

console.info(symbol.asSVG());
```

I get the expected output. Whether this is a change to the documentation (I didn't see it in the README) or needing a fix to `asSVG`, I don't know. Again, thanks for a neat library!

**Comment by spatialillusions** [comment]
Are you using the master branch or a released version? The removal of getMarker has just been made in the master branch, see the changelog. Released versions should include documentation that mentions getMarker, but it has been removed from the documentation in the master branch since it isn't needed anymore.
The master branch code is however backward compatable, so it will work if you use getMarker as well as without.

**Comment by gonzofish** [comment]
Oh! Well that makes sense. I'm using v0.6.0 through NPM, so the README here and in there probably don't match. I'll be closing this. Thanks!
