### ISSUE TITLE
Adding support for tactical points in APP6-B

### ISSUE THREAD

**Issue by spatialillusions** [spatialillusions/milsymbol#83]
TODO

**Comment by spatialillusions** [comment]
I have created a csv file with sidc and started to populate it with what geometries they have. I will see if I can get the correct mappings from https://mipsite.lsec.dnd.ca but the site has been down during the weekend. Otherwise I will just have to guess... 
It was bigger differences compared to 2525C than I initially thought it would be, but I will start populating the points during the week.

**Comment by halwaxt** [comment]
Mans,

The MIP site has moved to a new domain: https://www.mip-interop.org/

Best regards,
Thomas

Am 12.02.2017 um 23:05 schrieb Måns Beckman <notifications@github.com<mailto:notifications@github.com>>:


I have created a csv file with sidc and started to populate it with what geometries they have. I will see if I can get the correct mappings from https://mipsite.lsec.dnd.ca but the site has been down during the weekend. Otherwise I will just have to guess...
It was bigger differences compared to 2525C than I initially thought it would be, but I will start populating the points during the week.

**Comment by spatialillusions** [comment]
Thank you very much for the information! I tried to google everything but wasn't able to find it during the weekend. IIRC there is a Access database with mappings from SIDC to geometry types.

Do you know if there is any easier way to access the mappings, like an excel chart or csv file?

**Comment by spatialillusions** [comment]
Will start digging here and make some assumptions.
https://www.mip-interop.org/Public%20Document%20Library/Forms/AllItems.aspx?RootFolder=%2FPublic%20Document%20Library%2F04-Baseline_3%2E1%2FInterface-Specification%2FMIR%2FANNEX%20F%20-%20Geometry%20Rules&FolderCTID=0x012000CDEC559A618DF74781A1E0AE00DB1626&View={1DE80D78-9CC7-43F2-BDA0-08741E0F35E7}

**Comment by spatialillusions** [comment]
All icons are now in place, there is a preview available here:
http://spatialillusions.com/milsymbol-dev/docs/milsymbol-APP6b-tactical-points-svg.html
Will try to do all labels during the weekend.
