### ISSUE TITLE
Move to ES6

### ISSUE THREAD

**Issue by okwolf** [spatialillusions/milsymbol#88]
Saw this mentioned in #9, which is now closed. Now that you're using webpack it shouldn't be difficult to add babel transpilation to the build process while browsers don't yet support ES2015, but then your codebase will be ready for removing this step when support arrives. Which features from ES6 you want to use are up to you, but I would recommend at least looking at the modules for cleaner imports/exports.

**Comment by spatialillusions** [comment]
When I started moving to webpack I actually started out using ES6 modules, but in the beta of webpack I was using there was a bug in the output, so I moved over to using classic require instead, since then the bug in webpack has been solved so now there shouldn't be anything that prevents that.

This is one of those things that I have considered that it would be nice to do before releasing 1.0.0, but at the same time I have something that I'm quite sure is working now, so I rather keep things as they are. 

It should however be quite a simple change to make, so if anyone wants to help out it would be appreciated. Otherwise it will be done after the release of 1.0.0. (My main focus now is finishing APP6-B tactical points so that all features planned for 1.0.0 will be implemented.)

**Comment by okwolf** [comment]
Thanks for the update. No rush on this, I was just curious if it was still on your radar. Thanks!

**Comment by spatialillusions** [comment]
Since I sort of lack the knowledge of what would be considered "cleaner imports/exports", it would be really nice if someone else could have a look at this and make a pull. Feel free to modify file structure if needed.

**Comment by okwolf** [comment]
This file needs the most love re code splitting before moving to using modules: https://github.com/spatialillusions/milsymbol/blob/master/src/ms/iconparts.js

**Comment by spatialillusions** [comment]
Yes it should be split up and loaded in the same way as I do for tactical points, but it is a bit tricky to do this since it's not that simple that ground only uses icon parts with the prefix GR. To put it simply, it's a mess because it has grown organically over several years. 
I think that a good time to do this is at the same time as I implement 2525D/APP6D. 
The good thing is that there already is code in place to load separate icon parts part by part, so it is mostly about reorganizing things, but the big thing is doing it without breaking anything else...

**Comment by spatialillusions** [comment]
I just made some changes to how addIconParts works and made the tactical points for 2525 and APP6 load the icon parts they need automatically. This should prepare for loading smaller sets of icon parts when they are needed. Now I just need to break up the icon parts file into several smaller chunks in some way.

**Comment by okwolf** [comment]
#146 is a step in this direction since Rollup come with ES6 module support built-in.

**Comment by spatialillusions** [comment]
@okwolf Could you have a look at the ES6 branch that I just uploaded? 
https://github.com/spatialillusions/milsymbol/tree/es6

It is a simple convert of the code to ES6 so there is still a lot of work to do and next step is to make it into proper modules. The code builds and runs without any problems now, but the tests fails. I tried to use babel to get them working again but didn't have any luck. Would be super if you might do your magic to get them running again, then I can move this into the master branch and continue there.

**Comment by okwolf** [comment]
@spatialillusions see #155.

**Comment by spatialillusions** [comment]
@okwolf You sir, are as always, amazing.

**Comment by okwolf** [comment]
@spatialillusions what other features from ES6 do you want to adopt?

**Comment by spatialillusions** [comment]
My idea here is that it should be possible to import only the base `ms` object, that would contain all functionality but no iconparts or sidc, and then have each part of the standard as their own module that returned the sidcs and the required symbol parts in an object. So your pesudo code in the application would be like:
```js 
import {ms} from "milsymbol";
import letter_land_unit from "letter_sidc";
ms.addSymbols(letter_land_unit);
```
I'm still not sure if this is possible or if it makes sense, but it is one of the ideas that I'm having.

**Comment by okwolf** [comment]
Another option would be to have different versions of `ms` available which come pre-wired with subsets of `iconparts` imported. For example, keep the original one:

```js
import ms from "milsymbol";
```

and maybe add options like:

```js
import ms from "milsymbol/ground";
```

or:

```js
import ms from "milsymbol/air";
```

This would be similar to how lodash has: `"lodash"` vs `"lodash/fp"`.

**Comment by spatialillusions** [comment]
That is also an option that should be investigated. In that case we would have to consider how to import ground _and_ air at the same time, would they then be two separate objects or would it be possible to merge them.

**Comment by okwolf** [comment]
That depends on how many different use cases you would like to support. IMHO there should always be a full-featured `ms` available that supports all SIDC out-of-the-box as well as small subsets of that for saving size when that's all the functionality you need. Allowing mixing and matching at a level in between would be cool, but at least there's the full version to meet their needs.

**Comment by spatialillusions** [comment]
I totally agree with you here. Need to spend some more thinking about this and get back with a more detailed suggestion when I have done some prototyping.

**Comment by spatialillusions** [comment]
At the moment we won't make any more major changes to this, for additional ES6 support, please add new issues.
