### ISSUE TITLE
Minefields SIDC

### ISSUE THREAD

**Issue by gsl123** [spatialillusions/milsymbol#90]
I am currently doing some work on 2525D/APP6D and I have come across 4 SIDCs and I don't know where they have come from, they seem to carry on from where both 2525D & APP6D finish, does anyone have any idea where they came from?

10002500002707080000 Protection Areas Minefield AP Minefield
10002500002707090000 Protection Areas Minefield AT Minefield
10002500002707100000 Protection Areas Minefield Unspecified Minefield
10002500002707110000 Protection Areas Minefield Unspecified Minefield Decoy

**Comment by spatialillusions** [comment]
No idea where they come from. I have looked in drafts of both 2525D and APP6D and can't find them there.

I will close this issue, since it is not related to milsymbol. At the moment the plan is to implement tactical points for 2525D/APP6D when they are made public. You can contact me via email, found on homepage, if you have any further questions.
