### ISSUE TITLE
JavaScript Coding Standards

### ISSUE THREAD

**Issue by okwolf** [spatialillusions/milsymbol#97]
I couldn't find reference to any specific code standards on this repo, so I'm curious what your preferences (if any) are.

The best and most popular JavaScript static analysis/code quality tool around (I've used it on all my projects in the past six months) is [ESLint](http://eslint.org). It comes with a set of recommended rules (eslint:recommended) but is highly configurable and extendable from existing configs and plugins. It also plugs in nicely with webpack to automate the enforcement of whatever rules you decide to abide by in all code that gets bundled.

On the subject of formatting, ESLint does come with some basic formatting rules related to spacing and newlines, but the better solution there I've started using more recently is known as [prettier](https://github.com/prettier/prettier). It has the unique advantage that it knows how to fix all formatting related issues and can also play nicely with ESLint.

Would you be interested in including any of this as part of the build process?

**Comment by spatialillusions** [comment]
I have been trying to follow http://javascript.crockford.com/code.html for new code I have been writing, and I had a plan to update all source, but I haven't been able to do so because of lack of time.

To put it simply I don't have any special preferences, so if you have any preferences and are willing to integrate it into the build process, please go ahead. Prettier sound like a good idea, and I think we should follow some standard and not make up our own, but like I said before, I don't really have any preferences, so you can pick one.

The contributing.md should be updated with this information once it is in place, so that others know how to code.

**Comment by okwolf** [comment]
I tried running ESLint using `eslint:recommended` against the current codebase, and these were the types of errors I found:

- [no-unused-vars](http://eslint.org/docs/rules/no-unused-vars) - this could probably be downgraded to a warning, but it's still good code hygiene to remove them.
- [no-console](http://eslint.org/docs/rules/no-console) - similar to above this could be made a warning, but it's generally bad practice to leave console.logs in production code.
- [no-redeclare](http://eslint.org/docs/rules/no-redeclare) - This one can happen in a few different situations, such as redeclaring a local variable with the same name as a function parameter: https://github.com/spatialillusions/milsymbol/blob/master/src/symbol/ascanvas.js#L105
- [no-undef](http://eslint.org/docs/rules/no-undef) - This mostly results from referring to a `window.variable` without the `window.`

Are any of these things you would not be willing to enforce as part of the coding standard?

**Comment by spatialillusions** [comment]
no-unused-vars: 
I think that is because there are a lot of functions that looks the same, and I have wanted to keep the same structure, but I think the best solution here is just to comment them out.

no-console:
console.info - It logs when it is initialized and displays the version and library name on the console, easy way to check the version if something isn't working. (And also an easy way for me to check systems that I think use my code if it really is so.) Would like to keep this one.
console.warn - It also logs warnings if you try to use functionality that you have removed from a custom build. It shouldn't normally run, but it is a good way to show if anything is broken I think. Could be removed.
console.log - Then there is a bunch of console.log that warns that things are depreciated and they really should be console.warn. This should be changed until they are removed.

no-redeclare:
This is by mistake, should be changed to a different name. (Good bug to find.)

no-undef:
Would be interesting to know where `window.variable`s are called without `window`. This would probably just be a mistake by me. In most cases where I use window there is a backup if it doesn't work, so server rendering should work, but it could be good to look into. 

So most things could be fixed as long as it is possible to keep some console.info and console.warn. 

(And great work by the way!)

**Comment by spatialillusions** [comment]
I did some minor code cleaning, adding and removing ';' and changed console.log to console.warn. When it comes to changing != to !== and == to ===, this must be checked a bit more carefully, because I have tried this before and did run into some trouble.

But all additional cleaning, coding standard enforcements in the code is welcomed. 😀

**Comment by spatialillusions** [comment]
Have you done any tests running prettier on milsymbol? I did some reading and think it sounds like a good idea, would suggest two space indentation and to use semicolons. If you are used to use it I wouldn't mind a pull instead of me messing things up.
(Thinking about doing a new release during the weekend, so something like this could be a good idea to implement after that.)

**Comment by spatialillusions** [comment]
@okwolf I did some testing and ran prettier on all files using default settings, and I think the result is really nice. But like you mentioned before it might be a good idea to combine it with some eslint to validate the code as well. Have you any ideas of the best way to move forward on this to make sure all code looks good and is correct?

**Comment by okwolf** [comment]
@spatialillusions take a look at pull request #99

**Comment by spatialillusions** [comment]
Great work! I was thinking about doing something similar, but you are the one with experience here. I think we can close this issue now that we have automatic syntax validation and fixing built into the build process. Or do you have another opinion?

**Comment by okwolf** [comment]
@spatialillusions I think we just need to add a note in CONTRIBUTING.md and then we can close this out.

**Comment by spatialillusions** [comment]
I have updated contributing.md.
